version: '3.9'

services:
  WeatherTop:
    build:
      context: .
      dockerfile: Dockerfile
    image: weathertop:latest
    env_file: .env
    depends_on:
      - weathertop-postgres17
    ports:
      - "80:80"
  weathertop-postgres17:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: weathertop-postgres17:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
volumes:
  postgres-data: